### PR TITLE
Match topnav to design #713205417848078

### PR DESCRIPTION
**Pull request by hanchang**
https://app.asana.com/0/683768070860536/713205417848078

### CODE REVIEW

**Comment by MythicalFish** [comment]
Needs work IMO, also I think the page content should be full-width too.

**Comment by cryptoB0T** [comment]
the code change LGTM! not going to checkout the branch and test the visual design :shipit:

**Comment by hanchang** [comment]
@MythicalFish What changes are recommended other than the page content being full width? I was hesitant to switch page content to full width in this PR because it may impact other functionalities, so I was planning to handle that work in a different ticket most likely for v2.

@cryptoB0T You can use the Review App (just click the "View deployment" button) to look at visual changes / do any sort of testing without having to checkout the branch yourself.

**Comment by hanchang** [comment]
@MythicalFish Thanks for the catch on the login/logout button, the margin was indeed off!

**Pull request merged**
